"""initial schema

Revision ID: 2f201cef15a3
Revises: 
Create Date: 2026-07-18 18:30:46.831800

"""
from typing import Sequence, Union

import labcore.models.base
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f201cef15a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accession_counter',
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('entity_type', 'year')
    )
    op.create_table('entity_registry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('accession', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', labcore.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', labcore.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['entity_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_registry_accession'), 'entity_registry', ['accession'], unique=True)
    op.create_index(op.f('ix_entity_registry_created_by_id'), 'entity_registry', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_entity_registry_entity_type'), 'entity_registry', ['entity_type'], unique=False)
    op.create_table('analysis_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('git_commit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['entity_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_run_name'), 'analysis_run', ['name'], unique=False)
    op.create_table('artifact',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('checksum_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('media_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['entity_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifact_name'), 'artifact', ['name'], unique=False)
    op.create_table('cooldown',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', labcore.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('ended_at', labcore.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('base_temp_mk', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['entity_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cooldown_name'), 'cooldown', ['name'], unique=False)
    op.create_table('design_revision',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('git_commit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['entity_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_revision_name'), 'design_revision', ['name'], unique=False)
    op.create_table('device',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('device_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['entity_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_name'), 'device', ['name'], unique=False)
    op.create_table('die',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('wafer_position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['entity_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_die_name'), 'die', ['name'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('at', labcore.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['entity_registry.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entity_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_action'), 'event', ['action'], unique=False)
    op.create_index(op.f('ix_event_actor_id'), 'event', ['actor_id'], unique=False)
    op.create_index(op.f('ix_event_at'), 'event', ['at'], unique=False)
    op.create_index(op.f('ix_event_entity_id'), 'event', ['entity_id'], unique=False)
    op.create_table('fab_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['entity_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fab_run_name'), 'fab_run', ['name'], unique=False)
    op.create_table('instrument',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['entity_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instrument_name'), 'instrument', ['name'], unique=False)
    op.create_table('mask_set',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['entity_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mask_set_name'), 'mask_set', ['name'], unique=False)
    op.create_table('measurement_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', labcore.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['entity_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurement_run_name'), 'measurement_run', ['name'], unique=False)
    op.create_table('note',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['entity_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_name'), 'note', ['name'], unique=False)
    op.create_table('person',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tailscale_login', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['entity_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_name'), 'person', ['name'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['entity_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_name'), 'project', ['name'], unique=False)
    op.create_table('provenance_edge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('src_id', sa.Uuid(), nullable=False),
    sa.Column('dst_id', sa.Uuid(), nullable=False),
    sa.Column('relation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', labcore.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dst_id'], ['entity_registry.id'], ),
    sa.ForeignKeyConstraint(['src_id'], ['entity_registry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('src_id', 'dst_id', 'relation')
    )
    op.create_index(op.f('ix_provenance_edge_dst_id'), 'provenance_edge', ['dst_id'], unique=False)
    op.create_index(op.f('ix_provenance_edge_relation'), 'provenance_edge', ['relation'], unique=False)
    op.create_index(op.f('ix_provenance_edge_src_id'), 'provenance_edge', ['src_id'], unique=False)
    op.create_table('review_task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['entity_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_task_name'), 'review_task', ['name'], unique=False)
    op.create_table('wafer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('material', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('diameter_mm', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['entity_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wafer_name'), 'wafer', ['name'], unique=False)
    op.create_table('agent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('operator_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['entity_registry.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_name'), 'agent', ['name'], unique=False)
    op.create_table('fab_step',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('fab_run_id', sa.Uuid(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('recipe', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint('step_index >= 0'),
    sa.ForeignKeyConstraint(['fab_run_id'], ['fab_run.id'], ),
    sa.ForeignKeyConstraint(['id'], ['entity_registry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fab_run_id', 'step_index')
    )
    op.create_index(op.f('ix_fab_step_fab_run_id'), 'fab_step', ['fab_run_id'], unique=False)
    op.create_index(op.f('ix_fab_step_name'), 'fab_step', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fab_step_name'), table_name='fab_step')
    op.drop_index(op.f('ix_fab_step_fab_run_id'), table_name='fab_step')
    op.drop_table('fab_step')
    op.drop_index(op.f('ix_agent_name'), table_name='agent')
    op.drop_table('agent')
    op.drop_index(op.f('ix_wafer_name'), table_name='wafer')
    op.drop_table('wafer')
    op.drop_index(op.f('ix_review_task_name'), table_name='review_task')
    op.drop_table('review_task')
    op.drop_index(op.f('ix_provenance_edge_src_id'), table_name='provenance_edge')
    op.drop_index(op.f('ix_provenance_edge_relation'), table_name='provenance_edge')
    op.drop_index(op.f('ix_provenance_edge_dst_id'), table_name='provenance_edge')
    op.drop_table('provenance_edge')
    op.drop_index(op.f('ix_project_name'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_person_name'), table_name='person')
    op.drop_table('person')
    op.drop_index(op.f('ix_note_name'), table_name='note')
    op.drop_table('note')
    op.drop_index(op.f('ix_measurement_run_name'), table_name='measurement_run')
    op.drop_table('measurement_run')
    op.drop_index(op.f('ix_mask_set_name'), table_name='mask_set')
    op.drop_table('mask_set')
    op.drop_index(op.f('ix_instrument_name'), table_name='instrument')
    op.drop_table('instrument')
    op.drop_index(op.f('ix_fab_run_name'), table_name='fab_run')
    op.drop_table('fab_run')
    op.drop_index(op.f('ix_event_entity_id'), table_name='event')
    op.drop_index(op.f('ix_event_at'), table_name='event')
    op.drop_index(op.f('ix_event_actor_id'), table_name='event')
    op.drop_index(op.f('ix_event_action'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_die_name'), table_name='die')
    op.drop_table('die')
    op.drop_index(op.f('ix_device_name'), table_name='device')
    op.drop_table('device')
    op.drop_index(op.f('ix_design_revision_name'), table_name='design_revision')
    op.drop_table('design_revision')
    op.drop_index(op.f('ix_cooldown_name'), table_name='cooldown')
    op.drop_table('cooldown')
    op.drop_index(op.f('ix_artifact_name'), table_name='artifact')
    op.drop_table('artifact')
    op.drop_index(op.f('ix_analysis_run_name'), table_name='analysis_run')
    op.drop_table('analysis_run')
    op.drop_index(op.f('ix_entity_registry_entity_type'), table_name='entity_registry')
    op.drop_index(op.f('ix_entity_registry_created_by_id'), table_name='entity_registry')
    op.drop_index(op.f('ix_entity_registry_accession'), table_name='entity_registry')
    op.drop_table('entity_registry')
    op.drop_table('accession_counter')
    # ### end Alembic commands ###
